// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cknuljotpqxlhgiovahy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrbnVsam90cHF4bGhnaW92YWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjkyNjcsImV4cCI6MjA2NDAwNTI2N30.5UfOZxqNTyx8qp2VhwFxHCuA0Oz_ujClm0wzqxh4I24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);